apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14.2